variables:
- name: dockerfilePath
  value: Dockerfile
- group: social-network-var-group

steps:

- task: Go@0
  displayName: 'Install dependencies'
  inputs:
    command: 'custom'
    customCommand: mod 
    arguments: download

- task: Go@0
  displayName: Run tests
  inputs:
    command: 'test'

- script: |
    python3 -m pip install --upgrade pip
    pip3 install jinja2
  displayName: 'Install Jinja2'

- bash: |
    version=$(git log -1 --date='short' --format='%h-%ad')
    echo "##vso[task.setvariable variable=tag;isoutput=true]$version"
  displayName: Set version to short hash
  name: tag

- script: echo $(tag.tag)

- task: Bash@3
  displayName: Render deployment
  inputs:
    targetType: 'inline'
    script: |
      tag=$(tag.tag) ./ci/common
    failOnStderr: true
  #  workingDirectory: "$(System.DefaultWorkingDirectory)/"
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: deployment
    PathtoPublish: '$(build.artifactstagingdirectory)' 

- script:
    cat $(build.artifactstagingdirectory)/deployment.yml       

- task: Docker@2
  displayName: Build and push an image to Artifact Registry
  inputs:
    command: buildAndPush
    repository: $(IMAGE_REPOSITORY)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(ARTIFACT_REGISTRY_SERVICE_CONNECTION)
    tags: $(tag)
