#!/bin/bash

scriptpath="$(readlink -f "$0")"
workdir="${scriptpath%/*}"
cd "${workdir}/.."


version=$(git log -1 --date='short' --format='%h-%ad')


echo "Render deployment template with variables":


python3 ci/scripts/render_templates.py deployment.yml.j2 \
                                --api_port="$API_PORT" \
                                --token_hour_lifespan="$TOKEN_HOUR_LIFESPAN" \
                                --database_connection_string="$DATABASE_CONNECTION_STRING" \
                                --service_account_key="$SERVICE_ACCOUNT_KEY" \
                                --project_id="$PROJECT_ID" \
                                --api_secret="$API_SECRET" \
                                --pubsub_topic="$PUBSUB_TOPIC" \
                                --image="europe-central2-docker.pkg.dev/$IMAGE_REPOSITORY:$version"
                                                               